[package]
name = "interstice-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "interstice-cli"
path = "src/main.rs"

[dependencies]
interstice-core = { path = "../interstice-core" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.49", features = ["full"] }
