abi_version = 1
name = "hello"
visibility = "Public"
authorities = []
module_dependencies = []
node_dependencies = []

[version]
major = 0
minor = 0
patch = 1

[[reducers]]
name = "init"
arguments = []

[[reducers]]
name = "hello"

[[reducers.arguments]]
name = "name"
field_type = "String"

[[reducers]]
name = "on_greeting_insert"

[[reducers.arguments]]
name = "inserted_row"

[reducers.arguments.field_type]
Named = "Greetings"

[[queries]]
name = "get_greetings"
arguments = []

[queries.return_type.Vec]
Named = "Greetings"

[[tables]]
name = "greetings"
type_name = "Greetings"
visibility = "Public"

[[tables.fields]]
name = "greeting"
field_type = "String"

[[tables.fields]]
name = "custom"

[tables.fields.field_type]
Named = "TestCustomType"

[tables.primary_key]
name = "id"
field_type = "U64"

[[subscriptions]]
reducer_name = "init"
event = "Init"

[[subscriptions]]
reducer_name = "on_greeting_insert"

[subscriptions.event.Insert]
node_selection = "Current"
module_name = "hello"
table_name = "greetings"

[type_definitions.Greetings.Struct]
name = "Greetings"

[[type_definitions.Greetings.Struct.fields]]
name = "id"
field_type = "U64"

[[type_definitions.Greetings.Struct.fields]]
name = "greeting"
field_type = "String"

[[type_definitions.Greetings.Struct.fields]]
name = "custom"

[type_definitions.Greetings.Struct.fields.field_type]
Named = "TestCustomType"

[type_definitions.TestCustomType.Struct]
name = "TestCustomType"

[[type_definitions.TestCustomType.Struct.fields]]
name = "val"
field_type = "U32"
