name = "MyNode"
address = "127.0.0.1:8080"

[[modules]]
abi_version = 1
name = "hello"
visibility = "Public"
subscriptions = []
authorities = []
module_dependencies = []
node_dependencies = []

[modules.version]
major = 0
minor = 0
patch = 1

[[modules.reducers]]
name = "hello"

[[modules.reducers.arguments]]
name = "name"
field_type = "String"

[[modules.queries]]
name = "get_greetings"
arguments = []

[modules.queries.return_type.Vec]
Named = "Greetings"

[[modules.tables]]
name = "greetings"
type_name = "Greetings"
visibility = "Public"

[[modules.tables.fields]]
name = "greeting"
field_type = "String"

[[modules.tables.fields]]
name = "custom"

[modules.tables.fields.field_type]
Named = "TestCustomType"

[modules.tables.primary_key]
name = "id"
field_type = "U64"

[[modules.tables.indexes]]
field_name = "greeting"
index_type = "BTree"
unique = true

[modules.type_definitions.Greetings.Struct]
name = "Greetings"

[[modules.type_definitions.Greetings.Struct.fields]]
name = "id"
field_type = "U64"

[[modules.type_definitions.Greetings.Struct.fields]]
name = "greeting"
field_type = "String"

[[modules.type_definitions.Greetings.Struct.fields]]
name = "custom"

[modules.type_definitions.Greetings.Struct.fields.field_type]
Named = "TestCustomType"

[modules.type_definitions.TestCustomType.Struct]
name = "TestCustomType"

[[modules.type_definitions.TestCustomType.Struct.fields]]
name = "val"
field_type = "U32"
