[package]
name = "interstice-abi"
version = "0.0.1"
edition = "2024"

[dependencies]
serde = "*"
postcard = { version = "*", features = ["alloc"] }
toml = "*"
interstice-abi-macros = { path = "../interstice-abi-macros" }
bitflags = "*"
