[package]
name = "interstice-abi"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0"
postcard = { version = "1.1.3", features = ["alloc"] }
toml = "0.9"
interstice-abi-macros = { path = "../interstice-abi-macros" }
bitflags = { version = "2.10", features = ["serde"] }
