[package]
name = "test-hello"
version = "0.0.1"
edition = "2021"

[dependencies]
interstice-abi = { path = "../../crates/interstice-abi" }
interstice-core = { path = "../../crates/interstice-core" }
wasmtime = "*"
anyhow = "*"
