[package]
name = "interstice-core"
version = "0.0.1"
edition = "2024"

[dependencies]
interstice-abi = { path = "../../crates/interstice-abi" }
wasmtime = { version = "*", features = ["component-model"] }
anyhow = "*"
thiserror = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
slotmap = "*"
parking_lot = "*"
crossbeam = "*"                                              # later for scheduling
