[package]
name = "interstice-core"
version = "0.0.1"
edition = "2024"

[dependencies]
interstice-abi = { path = "../../crates/interstice-abi" }
wasmtime = { version = "*", features = ["component-model"] }
anyhow = "*"
serde = { version = "*", features = ["derive"] }
wgpu = "*"
winit = "*"
pollster = "*"
uuid = { version = "*", features = ["v4"] }
