abi_version = 1
name = "hello"
tables = []
subscriptions = []
authorities = []

[version]
major = 0
minor = 0
patch = 1

[[reducers]]
name = "hello"
return_type = "Void"

[[reducers.arguments]]
name = "name"
field_type = "String"

[type_definitions]
